services:
  - type: web
    name: miss-mister-primavera-portal
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SYNC_TOKEN
        generateValue: true
      - key: DATABASE_URL
        sync: false
